### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder-core#1]

**Comment by adamltyson** [comment]
I think everything should already work on macOS. What we need to do:
* Check it works (ideally on multiple systems)
* Add wheel building to github actions
* Check wheels work across OS versions
* Add to documentation, setup.py etc.

**Comment by adamltyson** [comment]
Add dev instructions for zsh.

**Comment by stephenlenzi** [comment]
> Add dev instructions for zsh.

https://www.gitmemory.com/issue/mu-editor/mu/852/498769312

**Comment by adamltyson** [comment]
Also install python from conda-forge on a mac seems to both speed up cellfinder and also allow napari to run on big sur.

**Comment by adamltyson** [comment]
On older os (e.g. <10.13) may need to install some packages from conda-forge. e.g. `conda install -c conda-forge scikit-learn`

**Comment by adamltyson** [comment]
Appears to work ok, but some issues:
* Installation on older OSs (<10.13)
* On one machine, issue with napari plugin & multiprocessing

**Comment by adamltyson** [comment]
Added in 463ffd7c94edd54de3dd011e147d0709a31dea3e
