### ISSUE TITLE
Standardise on one of "plane" or "layer"

### ISSUE THREAD

**Issue by dstansby** [brainglobe/cellfinder-core#136]
We (well, mainly me 😄 ) seem to be using "plane" and "layer" interchangably throughout the cell detection code, both in variable names and documentation. We should use one and standardise this across the codebase.

Any opinions?

**Comment by alessandrofelder** [comment]
I'd say "plane" is the commonly used word to denote the x-y plane in a 3d image stack.
(Using plane has the extra advantage that we don't risk confusing it with napari layers?)
