### ISSUE TITLE
`split_cells` expects `Sequence[Point]` but receives `ndarray`, causes error

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder-core#158]
When running the example in the README (or using `cellfinder-napari`), I get the following error:

```
  File "/home/adam/projects/brainglobe/cellfinder-core/src/cellfinder_core/main.py", line 69, in main
    points = detect.main(
  File "/home/adam/projects/brainglobe/cellfinder-core/src/cellfinder_core/detect/detect.py", line 167, in main
    cells = mp_3d_filter.process(async_results, callback=callback)
  File "/home/adam/projects/brainglobe/cellfinder-core/src/cellfinder_core/detect/filters/volume/volume_filter.py", line 102, in process
    return self.get_results()
  File "/home/adam/projects/brainglobe/cellfinder-core/src/cellfinder_core/detect/filters/volume/volume_filter.py", line 147, in get_results
    cell_centres = split_cells(
  File "/home/adam/projects/brainglobe/cellfinder-core/src/cellfinder_core/detect/filters/volume/structure_splitting.py", line 132, in split_cells
    xs = np.array([p.x for p in cell_points])  # TODO: use dataframe
  File "/home/adam/projects/brainglobe/cellfinder-core/src/cellfinder_core/detect/filters/volume/structure_splitting.py", line 132, in <listcomp>
    xs = np.array([p.x for p in cell_points])  # TODO: use dataframe
AttributeError: 'numpy.ndarray' object has no attribute 'x'
```

`cellfinder_core.detect.filters.volume.structure_splitting.split_cells` expects `Sequence[Point]` based on the type hints, but receives a numpy array, which doesn't have the correct attributes to be processed.

**Comment by dstansby** [comment]
Can you:
- Post the exact call to cellfinder
- Isolate which plane the `VolumeFilter` is processing when this error happens. Turning on logging should help here.
- Post a link to the data you're processing

I'm hoping with these three bits of information I'll be able to isolate a subset of data from the data you're trying to process that reliably reproduces the error, so we can include it in the test suite.

**Comment by adamltyson** [comment]
Has this been fixed? I can't reproduce on macOS. I originally tested on an Ubuntu machine, so I will test on that machine tommorow.

**Comment by dstansby** [comment]
I don't think it's been fixed

**Comment by dstansby** [comment]
If you've got those 30 planes that are replicating the issue locally un-tarred, could you tar just them them up and upload them somewhere I can get at them? I'm hoping we could use them for a small(-ish) set of sample data to reproduce the issue and get coverage over the cell splitting code.

**Comment by adamltyson** [comment]
I can replicate it with [this 2GB subset](https://gin.g-node.org/BrainGlobe/sample_data/src/master/MS_cx_left_subset.zip) and the following code:

```
if __name__ == '__main__':
    from cellfinder_core.main import main as cellfinder_run
    from cellfinder_core.tools.IO import read_with_dask
    signal_array = read_with_dask("MS_cx_left_subset/2")
    background_array = read_with_dask("MS_cx_left_subset/4")
    detected_cells = cellfinder_run(signal_array, background_array, [5, 2, 2])
```
