### ISSUE TITLE
jp2 input format[Feature]

### ISSUE THREAD

**Issue by ranczlab** [brainglobe/cellfinder-core#171]
Does cellfinder (napari or command line) read jpeg2000 files? 
If not, would it be complicated to implement it?
cheers,
Ede

**Comment by adamltyson** [comment]
Hey @ranczlab,

The command line tool will be gradually phased out, and we won't be adding any new data loaders. You could create your own scripts using cellfinder-core and a Python package of your choice to load JPEG2000

Alternatively, the napari plugin will (should) work on any data you can load into napari. I don't know of a JPEG2000 loader off the top of my head, but if you ask at https://forum.image.sc, somebody may know. If one doesn't exist, creating a napari reader plugin is fairly straightforward.
