### ISSUE TITLE
[BUG] `conda install cellfinder-core==0.4.0` does not allow `pip` to read version correctly.

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/cellfinder-core#179]
(Making myself an issue to track solutions/experiments so far)

**Describe the bug**
In a clean conda/mamba environment, running
```sh
conda install -y cellfinder-core==0.4.0
conda list cellfinder-core
```
will successfully install `cellfinder-core` version `0.4.0`. But running
```sh
pip show cellfinder-core
```
will return a version of `0.0.0`.

This means that any conda install that requires cellfinder-core will fail the `pip check` step of the testing phase. See for example the [BrainGlobe package recipe](https://github.com/conda-forge/staged-recipes/pull/23136).

On the other hand,
```sh
pip install cellfinder-core==0.4.0
```
will get `pip show` _and_ `conda list` to correctly show version `0.4.0`.

**To Reproduce**
See above.

**Expected behaviour**
`pip show` (and `pip list`, `pip check`) should correctly identify version `0.4.0`.

**Computer used (please complete the following information):**

- OS: Linux (Ubuntu 22.04)

**Comment by willGraham01** [comment]
This is _not_ fixed by the dynamic versioning fix in `v0.4.1`. conda-installing this package still results in `pip` picking up a version of `0.0.0`.

**Comment by adamltyson** [comment]
But the new version isn't on conda forge yet?

**Comment by willGraham01** [comment]
It's reported in the "successful" build:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=707010&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=652
