### ISSUE TITLE
Fix macOS tests

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder-core#27]
Currently they time out on GH actions

**Comment by psobolewskiPhD** [comment]
OK, so noted in the #28 the tests started hanging on macOS here:
https://github.com/brainglobe/cellfinder-core/actions/runs/1238657988

I took a look at this PR and it seems fine, but playing around with it, I can narrow it down to the .txt reading part.
You can see in my branch where I comment out the .txt reading and test. I aded a DIR *.tif dask test to make sure it wasn't the Dask part. Now macOS tests pass normally:
https://github.com/psobolewskiPhD/cellfinder-core/tree/fix-mac-tests
https://github.com/psobolewskiPhD/cellfinder-core/runs/5024871110?check_suite_focus=true
(note i had some Black issues, where CI was using 22.1 and pre-commit was using 20.x and they kept changing each other back and forth failing each time...was fun!)

I have *no* idea why the text reading would trip up macOS...
Maybe something related to line endings or text formatting? I'll poke around a bit more, but I have zero experience with this sort of stuff. Maybe someone else has some ideas?

**Comment by dstansby** [comment]
I *think* this is an issue with the manual `Process`/`Lock` handling, based on the traceback when I interrupt a hanging build locally. I also think https://github.com/brainglobe/cellfinder-core/pull/49 fixes this - 3/3 CI runs I've done with that branch have passed on macOS.

**Comment by psobolewskiPhD** [comment]
I did `gh pr checkout 49` and on my M1 tests run and don't hang like before after completing.
I tried regular `pytest` and with `pytest-xdist`.
I guess I was on the right track:
>I suspect somewhere a something isn't closing or exiting cleanly, due to some multiprocessing issue (fork, etc.)
