### ISSUE TITLE
Use tox file when running tests on GH actions

### ISSUE THREAD

**Issue by paddyroddy** [brainglobe/cellfinder-core#32]
There's currently a tox file in the repository, but it's not used in CI testing. We should update the test file (see https://github.com/brainglobe/cellfinder-napari/blob/main/tox.ini for an example we're currently using) and then use it to run the tests on GH actions.

**Comment by dstansby** [comment]
I think we should be using the tox file for testing, to keep the way testing is run standardised across projects.  As such I've edited the title/description here.

**Comment by adamltyson** [comment]
Tox isn't used in most repos (only those created with the napari cookiecutter AFAIK), so removing tox would be closer to standardisation.

That being said, I'm happy to adopt it throughout if it's useful.

**Comment by dstansby** [comment]
Given we've setup the `BrainGlobe` actions to run the tests from a `tox` file, I think we should use it throughout. This has the benefits of running the tests in an isolated virtual environment that tox builds just for the tests, which makes the tests more reproducible across local runs and GH actions runs.

**Comment by adamltyson** [comment]
Sounds good to me.
