### ISSUE TITLE
Ensure all development requirements are in `extras_require={ "dev":...}`

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder-core#39]
Some new tooling has been added, e.g. `isort` and this should be in the development requirements so it's installed with `pip install -e .`.

**Comment by paddyroddy** [comment]
you don't need `isort` installed as it's managed by `pre-commit` i.e. `pre-commit` "installs" it

**Comment by adamltyson** [comment]
Yeah I know, but it's nice for developers to be able to run the tool themselves, especially if they're not familiar.

**Comment by paddyroddy** [comment]
Even so, it's easier to just run it via `pre-commit`

**Comment by paddyroddy** [comment]
well you can do i.e. `pre-commit run isort` haven't looked into parameters, but you can edit the config file
