### ISSUE TITLE
[BUG] Cython language_level warning

### ISSUE THREAD

**Issue by dstansby** [brainglobe/cellfinder-core#61]
When testing with `tox`, the following warning is raised:

```python
/Users/dstansby/projects/napari/cellfinder-core/.tox/.package/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/dstansby/projects/napari/cellfinder-core/src/cellfinder_core/detect/filters/plane/base_tile_filter.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
```
The important bit is
> Cython directive 'language_level' not set, using 2 for now (Py2).

I'm not sure whether this should be set to 2 or 3, but either way this should be manually set to avoid issues due to the default value potentially changing in future versions of Cython.

**Comment by paddyroddy** [comment]
I've had to do this before, and it only required `# cython: language_level=3` at the top of the file. We're in `python` 3 world now
