### ISSUE TITLE
Remove MANIFEST.in?

### ISSUE THREAD

**Issue by dstansby** [brainglobe/cellfinder-core#96]
I'm currenlty repeatedly bulding `cellfinder-core` to debug some of the Cython code. It seems like a significant amount of time is spent in `pip install -e .` reading the `MANIFEST.in` file. I don't think it's needed any more now because we're using `setuptools_scm`, which will include any files committed using git. So it would be good to double check this, and if I'm correct here remove `MANIFEST.in` to speed up building/installing the pakcage from source

**Comment by adamltyson** [comment]
For this repo it seems fine. Presumably if we have any `exclude` statements in other repos, we would still need `MANIFEST.in`?
