### ISSUE TITLE
Add a test for structure detection with different dtypes

### ISSUE THREAD

**Issue by dstansby** [brainglobe/cellfinder-core#98]
The structure detection code contains branches for data with different unsigned integer types:

https://github.com/brainglobe/cellfinder-core/blob/93e4b0d098d22e3eb3fba7ea9c658bf1602b1f60/src/cellfinder_core/detect/filters/volume/structure_detection.pyx#L108-L118

We should add a unit test that exercises all of these branches.

**Comment by dstansby** [comment]
Probably worth adding a comment about those 'magic values' that are being used as multipliers too. They seem to be:

- 2**56 + 2**48 + 2**40 + 2**32 + 2**24 + 2**16 + 2**8 - 2**4
- 2**48 + 2**32 + 2**16 + 1
- 2**32 + 1

Apart from being related to maximum values in each of those dtypes, I have no idea what exactly these mean

**Comment by adamltyson** [comment]
I can't remember what exactly they do, but features in the image are encoded on top of the image itself. Something like, if the image was 8 bit, then the max value is 255.  The information in the image would be between 0-255, but mostly (if acquired properly) at the bottom end. The intensity is then thresholded, and saved onto the data with value `max -1`, so 244. The cell centroids are then encoded into the image with value`max` (255). This way the raw data is kept in memory along with thresholding and the centroid finding, without holding any more data in RAM.

This may not be 100% accurate, but that's the general idea. It may not be the most efficient way to do this, but it seems to work well,
